### ISSUE TITLE
开局时出现程序崩溃

### ISSUE THREAD

**Issue by ouuan** [eee555/Solvable-Minesweeper#2]
连着开局多次后程序崩溃：

```
Traceback (most recent call last):
  File "/home/ouuan/GitHub/Solvable-Minesweeper/mineSweeperGUI.py", line 156, in mineAreaLeftRelease
    self.layMine(i,j)
  File "/home/ouuan/GitHub/Solvable-Minesweeper/mineSweeperGUI.py", line 87, in layMine
    Board , Parameters = minesweeper_master.layMineSolvable(xx , yy , num , i , j ,self.min3BV,self.max3BV, self.timesLimit , self.enuLimit)
  File "/home/ouuan/GitHub/Solvable-Minesweeper/minesweeper_master.py", line 568, in layMineSolvable
    if isSolvable(Board , X0, Y0,enuLimit):
  File "/home/ouuan/GitHub/Solvable-Minesweeper/minesweeper_master.py", line 470, in isSolvable
    MatrixA , Matrixx , Matrixb , BoardofGame , NotMine = SolveEnumerate(MatrixA , Matrixx , Matrixb , BoardofGame , enuLimit)
  File "/home/ouuan/GitHub/Solvable-Minesweeper/minesweeper_master.py", line 350, in SolveEnumerate
    AllTable = enuOneStep(AllTable , TableId , b)
  File "/home/ouuan/GitHub/Solvable-Minesweeper/minesweeper_master.py", line 397, in enuOneStep
    if AllTable[0][i] == 2:
IndexError: list index out of range
```

版本: 14ad3112501131bb12c481b9722db5220ff4d1b8

**Comment by eee555** [comment]
是的，就是这个数组越界，目前最难解决的bug（滑稽），过几个版本再解决哈哈哈

**Comment by eee555** [comment]
感谢您的反馈！
